# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/design_1_AXI4_Stream_to_Video_0_0.xci
# IP: The module: 'design_1_AXI4_Stream_to_Video_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/design_1_AXI4_Stream_to_Video_0_0.xci
# IP: The module: 'design_1_AXI4_Stream_to_Video_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Test/3_Study/nexys_video_microblaze_ov5640_20200321/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_AXI4_Stream_to_Video_0_0/src/axis2pix_fifo/axis2pix_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis2pix_fifo || ORIG_REF_NAME==axis2pix_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
